jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Zip the dist directory into release.zip
      - name: Zip artifact for deployment
        run: zip -r release.zip dist/*

      # Upload the release.zip as an artifact for the next job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Download the release.zip artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      # Unzip the release.zip into a directory named ./deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./deployment

      # Login to Azure using secrets
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DD602F67B8AC46F9AD8F807AB5A89060 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A818A957157548F2BF03641ACCE1539D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3A2541E107E14ABC8B44E521F21D22E4 }}

      # Deploy the contents of the ./deployment directory to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'crmmain'
          slot-name: 'Production'
          package: ./deployment
